package com.example.leetcode.challenge.test2020.september.week4;


/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindDifference {
    public char findTheDifference(String s, String t) {
        int[] sCount = new int[26];
        int[] tCount = new int[26];
        for (int i = 0; i < s.length(); i++) {
            sCount[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++) {
            tCount[s.charAt(i) - 'a']++;
        }
        int index = 0;
        while (index < 26){
            if(sCount[index] != tCount[index]){
                break;
            }
            index++;
        }
        return (char)('a'+index);
    }

    /**
     * faster solution
     * @param s
     * @param t
     * @return
     */
    public char findTheDifferenceV1(String s, String t) {
        int[] map = new int[26];

        for (char c : s.toCharArray()) {
            map[c-'a']++;
        }
        for (char c : t.toCharArray()) {
            map[c-'a']--;

            if (map[c-'a'] < 0) {
                return c;
            }
        }
        return 'a';
    }
}
