package com.example.leetcode.challenge.test2022.february;

/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 *
 * Input: s = "", t = "y"
 * Output: "y"
 */
public class FindDifference {
    public static void main(String[] args) {

    }

    public char findTheDifference(String s, String t) {
        int[] count = new int[26];
        int length = s.length();

        for (int i = 0; i < length; i++) {
            count[s.charAt(i) - 'a']++;
            count[t.charAt(i) - 'a']--;
        }
        count[t.charAt(t.length() - 1) - 'a']--;
        for (int i = 0; i < 26; i++) {
            if(count[i] == -1)
                return (char)('a' + i);
        }
        return 'a';
    }
}
